#!/usr/bin/env ansible-playbook
---
- name: create/restore server
  remote_user: root
  hosts: paupermc
  post_tasks:
  - name: create data directory
    ansible.builtin.file:
      path: /root/paupermc/data
      state: directory
  - block:
    - name: stop server
      community.docker.docker_container:
        image_name_mismatch: ignore
        name: paupermc
        state: stopped
    - name: copy world backup to server
      ansible.builtin.copy:
        dest: /root/paupermc/data/
        src: ./backups/paupermc_world_latest.tar
    - name: uncompress world
      ansible.builtin.shell:
        chdir: /root/paupermc/data
        cmd: tar -xf paupermc_world_latest.tar
    when: restore | default(False)
  pre_tasks:
  - name: configure sshd
    register: sshd
    ansible.builtin.blockinfile:
      block: |-
        PasswordAuthentication no
        AuthenticationMethods publickey
      insertafter: ^#PasswordAuthentication
      path: /etc/ssh/sshd_config
  - name: restart sshd
    when: sshd.changed
    ansible.builtin.systemd_service:
      name: sshd.service
      state: restarted
  - ansible.builtin.service_facts: {}
  - name: disable firewall
    when: ansible_facts.services['ufw.service'] is defined
    ansible.builtin.systemd_service:
      enabled: false
      name: ufw.service
      state: stopped
  roles:
  - role: ansible_role_docker
