#!/usr/bin/env ansible-playbook
---
- name: backup server
  remote_user: root
  hosts: paupermc
  tasks:
  - name: stop server
    community.docker.docker_container:
      name: paupermc
      state: stopped
  - name: create archive
    ansible.builtin.shell:
      chdir: /root/paupermc/data
      cmd: tar -cvpf ../paupermc_world_latest.tar world
  - name: download archive
    ansible.builtin.fetch:
      dest: ./backups/
      flat: true
      src: /root/paupermc/paupermc_world_latest.tar
