#!/usr/bin/env ansible-playbook
---
- name: start server
  remote_user: root
  hosts: paupermc
  tasks:
  - name: start server
    community.docker.docker_container:
      env:
        EULA: 'TRUE'
        VERSION: '{{ hostvars[inventory_hostname].mc_version | default(''1.16.1'') }}'
        MEMORY: 2G
        SEED: '{{ hostvars[inventory_hostname].seed | default('''') }}'
        ONLINE_MODE: 'FALSE'
        SPAWN_PROTECTION: '0'
      image: itzg/minecraft-server
      image_name_mismatch: ignore
      name: paupermc
      published_ports:
      - 0.0.0.0:25565:25565
      state: started
      volumes:
      - /root/paupermc/data:/data
