---
- name: start server container
  hosts: paupermc
  remote_user: root
  tasks:
    - name: start server
      community.docker.docker_container:
        name: paupermc
        image: itzg/minecraft-server
        image_name_mismatch: ignore
        state: started
        ports:
          - "0.0.0.0:25565:25565"
        volumes:
          - "/home/paupermc/data:/data"
        env:
          EULA: "TRUE"
          VERSION: "1.16.1"
          MEMORY: 2G